name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
        
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u mogensen --password-stdin
        
      - name: Build the Docker image
        run: docker build -t mogensen/my-best-recipes:nginx-$(date +'%Y-%m-%d-%H%M') .

      - name: Push the Docker image to the registry
        run: docker push mogensen/my-best-recipes:nginx-$(date +'%Y-%m-%d-%H%M')
